<?xml version="1.0" encoding="utf-8"?><Database Name="TradeShop" Class="TradeShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-HBID7S9\SQLEXPRESS;Initial Catalog=TradeShop;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TradeShop" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_ord" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_product" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DonDatHang_ChiTietDonHang" Member="DonDatHang" ThisKey="id_ord" OtherKey="id" Type="DonDatHang" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="SanPham" ThisKey="id_product" OtherKey="id" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMuc" Member="DanhMucs">
    <Type Name="DanhMuc">
      <Column Name="id_cat" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_cat" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="keywords" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(125)" CanBeNull="true" />
      <Association Name="DanhMuc_SanPham" Member="SanPhams" ThisKey="id_cat" OtherKey="id_cat" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.DonDatHang" Member="DonDatHangs">
    <Type Name="DonDatHang">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_buyer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_seller" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="time_ord" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="time_deliver" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total_payment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="time_rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="DonDatHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="id" OtherKey="id_ord" Type="ChiTietDonHang" />
      <Association Name="TaiKhoan_DonDatHang" Member="TaiKhoan" ThisKey="id_buyer" OtherKey="id_user" Type="TaiKhoan" IsForeignKey="true" />
      <Association Name="TaiKhoan_DonDatHang1" Member="TaiKhoan1" ThisKey="id_seller" OtherKey="id_user" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="product_price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="product_image" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descrip" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="time_add" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="time_edit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="id_cat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_user" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="id" OtherKey="id_product" Type="ChiTietDonHang" />
      <Association Name="DanhMuc_SanPham" Member="DanhMuc" ThisKey="id_cat" OtherKey="id_cat" Type="DanhMuc" IsForeignKey="true" />
      <Association Name="TaiKhoan_SanPham" Member="TaiKhoan" ThisKey="id_user" OtherKey="id_user" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="avatar" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="time_register" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="time_update" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="TaiKhoan_DonDatHang" Member="DonDatHangs" ThisKey="id_user" OtherKey="id_buyer" Type="DonDatHang" />
      <Association Name="TaiKhoan_DonDatHang1" Member="DonDatHangs1" ThisKey="id_user" OtherKey="id_seller" Type="DonDatHang" />
      <Association Name="TaiKhoan_SanPham" Member="SanPhams" ThisKey="id_user" OtherKey="id_user" Type="SanPham" />
    </Type>
  </Table>
</Database>